# Generated by Django 5.2.11 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_issue_options_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("RESOLVED", "Resolved"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
